### ISSUE TITLE
measuring tx/rx events

### ISSUE THREAD

**Issue by conjam** [mtcp-stack/mtcp#238]
Hey all, 
In the paper it is claimed "In our experiments with 8 RX/TX queues per 10 Gbps
port, the average number of events that an mTCP thread
generates in a single scheduling period is about 2,170
for both TX and RX directions"

Trying to recreate this, and I was curious how this was measured? 

EDIT: I realize this wasn't constructive:  I am curious if there are any tricks to vary batch size in a fine-grained way; I could either set epoll_max_events to be something artificially low to have small batches? I wasn't sure if there was another approach, my apologies for the vague inquiry.

**Comment by eunyoung14** [comment]
Well.. As you might have noticed, there aren't many ways to control the actual batch size in fine-grained manner because it depends on the schedulers. We just tried to solve it naturally by having an event loop. More events from the apps/NICs will induce larger batch size. If you'd like to maintain smaller batches, I recommend you to read less packets at a loop even though they remain at the buffer.

**Comment by conjam** [comment]
Makes sense, this is what I ended up going with. Thanks!
